# Generated by Django 4.1 on 2022-09-07 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='Uncategorized', max_length=200, null=True, verbose_name='Category')),
                ('Image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RenteeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120, verbose_name='User Name')),
                ('Email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120, verbose_name='Listing Name')),
                ('Location', models.CharField(max_length=120, verbose_name='Listing Location')),
                ('Description', models.TextField(default='In Good Shape', max_length=1000, verbose_name='Listing Description')),
                ('HourlyRate', models.IntegerField(default=None, verbose_name='HourlyRate')),
                ('DailyRate', models.IntegerField(default=None, verbose_name='DailyRate')),
                ('WeeklyRate', models.IntegerField(default=None, verbose_name='WeeklyRate')),
                ('MonthlyRate', models.IntegerField(default=None, verbose_name='MonthlyRate')),
                ('ListingImage', models.ImageField(default=None, upload_to='images/')),
                ('Contact', models.CharField(default=None, max_length=10, verbose_name='Listing Contact')),
                ('Category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.category')),
                ('Owneruser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
