# Generated by Django 4.1 on 2022-09-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
